"""Preflight artifact inventory for the v3 test-eval pass.

Writes:
  reports/preflight_inventory.md
  tables/preflight_artifacts.csv
"""
from __future__ import annotations

import csv
import glob
import json
import os
import sys
from pathlib import Path

REPO = Path("/groups/echambe2/gmeng/MedAL-Agent/repo/code")
RUNS_V1 = REPO / "runs" / "pilot_v1"
RUNS_V3 = REPO / "runs" / "test_eval_v3"
DATA_ROOT = Path("/groups/echambe2/datasets/data")
SAM_CACHE = Path("/groups/echambe2/gmeng/MedAL-Agent/cache/foundation_features")
REPORTS = REPO / "reports"
TABLES = REPO / "tables"

POLICIES = ["P0","P1","P2","P3","P4","P5","P6","P7","P8","P9"]
SEEDS = ["s1000","s2000","s3000"]
DATASETS = ["busi","cvc_clinicdb","isic2018","promise12"]
DATASET_ROOTS = {
    "busi": DATA_ROOT / "2d" / "busi",
    "cvc_clinicdb": DATA_ROOT / "2d" / "cvc_clinicdb",
    "isic2018": DATA_ROOT / "2d" / "isic2018_task1",
    "promise12": DATA_ROOT / "2d" / "promise12",
}
GROUP_KEY = {"busi":"none","cvc_clinicdb":"sequence (29; via metadata.csv)","isic2018":"none","promise12":"case (50; via filename Case_NN)"}


def main():
    # Cell-by-cell inventory
    rows = []
    for ds in DATASETS:
        for p in POLICIES:
            for sd in SEEDS:
                jpath = RUNS_V1 / f"{ds}__{p}__{sd}.jsonl"
                recs = []
                if jpath.exists():
                    recs = [json.loads(l) for l in open(jpath)]
                n_rounds = len(recs)
                total_selected = sum(len(r.get("selected_ids", [])) for r in recs)
                final_dsc = recs[-1]["metrics"]["mean_dsc_fg"] if recs else float("nan")
                final_hd95 = recs[-1]["metrics"].get("mean_hd95_fg", float("nan")) if recs else float("nan")
                ckpt_path = RUNS_V3 / "ckpts" / f"{ds}__{p}__{sd}__r5.pt"
                rows.append({
                    "dataset": ds, "policy": p, "seed": sd,
                    "v1_jsonl_exists": int(jpath.exists()),
                    "v1_rounds": n_rounds,
                    "v1_total_selected_ids": total_selected,
                    "v1_final_dsc": round(final_dsc, 4) if final_dsc == final_dsc else "nan",
                    "v1_final_hd95": round(final_hd95, 1) if final_hd95 == final_hd95 else "nan",
                    "v3_checkpoint_round5_exists": int(ckpt_path.exists()),
                })

    TABLES.mkdir(parents=True, exist_ok=True)
    with open(TABLES / "preflight_artifacts.csv", "w", newline="") as f:
        w = csv.DictWriter(f, fieldnames=list(rows[0].keys()))
        w.writeheader()
        for r in rows: w.writerow(r)

    # Markdown report
    L = []
    L.append("# v3 preflight artifact inventory")
    L.append("")
    L.append("Audit for the fair test-set evaluation pass (v3). Existing v1 selected_ids will be replayed;")
    L.append("no new active-learning trajectories are generated.")
    L.append("")
    L.append("---")
    L.append("")

    # JSONL coverage
    n_jsonl = len(list(RUNS_V1.glob("*.jsonl"))) - len(list(RUNS_V1.glob("_*"))) - len(list(RUNS_V1.glob("*msd07*")))
    L.append("## JSONL coverage (v1 trajectories)")
    L.append("")
    expected = len(DATASETS) * len(POLICIES) * len(SEEDS)
    present = sum(r["v1_jsonl_exists"] for r in rows)
    L.append(f"- expected: {expected} cells (4 datasets × 10 policies × 3 seeds)")
    L.append(f"- present:  {present}")
    L.append(f"- ratio:    {present/expected:.0%}")
    L.append("")
    if present == expected:
        L.append("✓ All v1 trajectories present.")
    else:
        L.append("⚠ Missing cells:")
        for r in rows:
            if not r["v1_jsonl_exists"]:
                L.append(f"  - {r['dataset']}/{r['policy']}/{r['seed']}")
    L.append("")

    # selected_ids
    L.append("## `selected_ids` availability")
    L.append("")
    L.append("Each v1 JSONL stores `selected_ids` per round (rounds 0–4; round 5 has none, final eval).")
    L.append("Sample rounds-and-counts:")
    L.append("")
    L.append("| dataset | policy | seed | rounds | total selected |")
    L.append("|---|---|---|---|---|")
    for r in rows[:6]:
        L.append(f"| {r['dataset']} | {r['policy']} | {r['seed']} | {r['v1_rounds']} | {r['v1_total_selected_ids']} |")
    L.append("| … | … | … | … | … |")
    L.append("")
    L.append(f"Full per-cell row in `tables/preflight_artifacts.csv` ({len(rows)} rows).")
    L.append("")
    L.append("**Caveat**: the initial labeled set (cold start) is NOT stored explicitly in `selected_ids`.")
    L.append("It is regenerated by `np.random.RandomState(cfg.seed)` shuffle of the train pool — same code path")
    L.append("as v1. The v3 replay reconstructs the labeled-set-at-round-r as: cold_start ∪ sum(selected_ids over rounds < r).")
    L.append("")

    # Splits
    L.append("## Train/val/test splits")
    L.append("")
    L.append("Splits are NOT saved to disk. They are reproduced from `runner/splits.make_split(adapter, seed=cfg.seed, val_frac=0.1, test_frac=0.1)`")
    L.append("at runtime. Group-safety per adapter:")
    L.append("")
    L.append("| dataset | group key | enforced by |")
    L.append("|---|---|---|")
    for ds in DATASETS:
        L.append(f"| {ds} | {GROUP_KEY[ds]} | `{ds}.py`: `patient_ids()` |")
    L.append("")
    L.append("`make_split` uses group-disjoint partitioning when `adapter.patient_ids() is not None`.")
    L.append("No slice-level leakage on PROMISE12. No sequence-level leakage on CVC.")
    L.append("Same `cfg.seed` → same split, deterministically. v3 will use the SAME `seed` as v1 for each cell, so")
    L.append("v3's val/test splits will be IDENTICAL to v1's val split (and v1's test split that was never evaluated).")
    L.append("")

    # Checkpoints
    n_ckpt = sum(r["v3_checkpoint_round5_exists"] for r in rows)
    L.append("## Checkpoints (v3 target)")
    L.append("")
    L.append(f"- checkpoints already present: {n_ckpt} / {expected}")
    L.append(f"- target: {expected} final-round checkpoints + (optionally) intermediate per-round checkpoints")
    L.append(f"- path: `runs/test_eval_v3/ckpts/{{dataset}}__{{policy}}__{{seed}}__r{{round}}.pt`")
    L.append("")
    L.append("**No v1 checkpoints exist** — `train_from_scratch` builds a fresh model per round in v1 and does not persist it.")
    L.append("v3 will save checkpoints as part of the test-eval pass.")
    L.append("")

    # Masks / adapters / datasets on disk
    L.append("## Masks / adapters / dataset roots")
    L.append("")
    L.append("| dataset | adapter | data root | status |")
    L.append("|---|---|---|---|")
    for ds in DATASETS:
        root = DATASET_ROOTS[ds]
        adapter = REPO / "medal_bench" / "data" / "adapters" / f"{ds}.py"
        status = "OK" if root.exists() and adapter.exists() else "MISSING"
        L.append(f"| {ds} | `medal_bench/data/adapters/{ds}.py` | `{root}` | {status} |")
    L.append("")
    L.append("All masks are accessible via the adapters' `__getitem__(i).mask`.")
    L.append("")

    # SAM cache
    L.append("## SAM feature cache (for P7/P8 + diagnostics)")
    L.append("")
    L.append(f"Path: `{SAM_CACHE}`")
    sam_files = list(SAM_CACHE.glob("*.h5"))
    L.append(f"Files present: {len(sam_files)}")
    for f in sorted(sam_files):
        L.append(f"  - `{f.name}` ({f.stat().st_size//1024} KB)")
    L.append("")

    # Conclusion
    L.append("---")
    L.append("")
    L.append("## Conclusion")
    L.append("")
    L.append(f"- v1 selected_ids: **{present}/{expected} cells** available ✓")
    L.append("- splits: reproducible from `make_split(seed)` ✓")
    L.append("- adapters + datasets on disk: ✓")
    L.append("- SAM cache: ✓")
    L.append("- v3 checkpoints: not yet produced (this is the deliverable of the v3 pass)")
    L.append("")
    L.append("**Ready to proceed with canary** (cvc_clinicdb/P0/s1000, rounds 0 and 5) followed by the full 120-cell matrix.")

    REPORTS.mkdir(parents=True, exist_ok=True)
    (REPORTS / "preflight_inventory.md").write_text("\n".join(L))
    print(f"wrote {REPORTS / 'preflight_inventory.md'}")
    print(f"wrote {TABLES / 'preflight_artifacts.csv'} ({len(rows)} rows)")


if __name__ == "__main__":
    main()
